create table reponse (idquestion integer,idreponse integer,reponse varchar(100),valeur integer, primary key(idquestion, idreponse));
insert into reponse (idquestion,idreponse,reponse,valeur) values ('1','0','Le systeme d information est accessoire a l accomplissement des missions','3');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('1','1','Le systeme d information est utile a l accomplissement des missions','1');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('1','2','Le systeme d information est necessaire a l accomplissement des missions','2');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('1','3','Le systeme d information est vital a l accomplissement des missions','3');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('2','0','Les consequences internes d un sinistre SSI ne peuvent qu etre negligeables','1');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('2','1','Les consequences internes d un sinistre SSI peuvent etre significatives','1');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('2','2','Les consequences internes d un sinistre SSI peuvent etre graves','2');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('2','3','Les consequences internes d un sinistre SSI peuvent etre fatales','3');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('3','0','Les consequences externes d un sinistre SSI ne peuvent qu etre negligeables','0');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('3','1','Les consequences externes d un sinistre SSI peuvent etre significatives','1');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('3','2','Les consequences externes d un sinistre SSI peuvent etre graves','2');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('3','3','Les consequences externes d un sinistre SSI peuvent etre catastrophiques','3');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('4','0','L inaccessibilite du(des) systeme(s) informatique(s) ne gene quasiment pas l activite','0');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('4','1','L inaccessibilite du(des) systeme(s) informatique(s) perturbe l activite de maniere significative','1');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('4','2','L inaccessibilite du(des) systeme(s) informatique(s) est jugee comme grave pour l activite','2');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('4','3','L inaccessibilite du(des) systeme(s) informatique(s) peut etre fatale pour l activite','3');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('5','0','L alteration des donnees ne gene quasiment pas l activite','0');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('5','1','L alteration des donnees perturbe l activite de maniere significative','1');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('5','2','L alteration des donnees est jugee comme grave pour l activite','2');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('5','3','L alteration des donnees peut etre fatale pour l activite','3');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('6','0','La compromission d informations ne gene quasiment pas l activite','0');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('6','1','La compromission d informations perturbe l activite de maniere significative','1');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('6','2','La compromission d informations est jugee comme grave pour l activite','2');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('6','3','La compromission d informations peut etre fatale pour l activite','3');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('7','0','Les sinistres SSI (vecus ou imaginables) sont rarissimes (moins d une fois par an)','0');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('7','1','Plusieurs sinistres SSI dans l annee','1');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('7','2','Plusieurs sinistres SSI par trimestre,','2');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('7','3','Plusieurs sinistres SSI par mois','3');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('8','0','Une attaque SSI ciblee sur le perimetre est relativement inimaginable','0');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('8','1','La motivation des attaquants potentiels est jugee faible','1');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('8','2','La motivation des attaquants potentiels peut etre forte','2');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('8','3','La motivation des attaquants potentiels peut etre tres importante','3');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('9','0','Les attaquants potentiels ne disposent que de faibles moyens','0');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('9','1','Les attaquants peuvent disposer de moyens significatifs','1');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('9','2','Les attaquants peuvent disposer de moyens importants','2');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('9','3','Les attaquants peuvent disposer de moyens potentiellement illimites','3');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('10','0','Le systeme d information est juge comme homogene','0');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('10','1','Le systeme d information est juge comme faiblement heterogene','1');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('10','2','Le systeme d information est juge comme fortement heterogene','2');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('10','3','Le systeme d information est juge comme extremement heterogene','3');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('11','0','Le systeme d information n est pas ouvert','0');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('11','1','Le systeme d information n est ouvert qu a des systemes internes','1');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('11','2','Le systeme d information est ouvert a des systemes externes mais sous controle','2');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('11','3','Le systeme d information est ouvert a des systemes externes hors de controle','3');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('12','0','Le systeme d information et son contexte sont juges stables','0');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('12','1','Le systeme d information et son contexte changent peu','1');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('12','2','Le systeme d information et son contexte changent relativement souvent','2');
insert into reponse (idquestion,idreponse,reponse,valeur) values ('12','3','Le systeme d information et son contexte change tres souvent','3');
